# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Valerie Buyse Psychiatry
tagline:             'A Jekyll theme'
description:         'Professional website of Valerie Buyse MD, practicing psychiatry in Northern Virginia for over 30 years.'
url:                 https://curtpw.github.io/buysepsychiatrycom
baseurl:             'https://curtpw.github.io/buysepsychiatrycom'
paginate:            5

# About/contact
author:
  name:              Valerie Buyse
  url:               http://buysepsychiatry.com/
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
